In [4]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

xls = pd.ExcelFile('Company_Data_Set.xlsx')
df1 = pd.read_excel(xls, 'Task')
df2 = pd.read_excel(xls, 'data')
df3 = pd.DataFrame(df2)

df2.describe()

ID  SF contacts      Employees   stand rank   Product P1  \
count   3217.000000  3217.000000    3217.000000  3217.000000  3217.000000   
mean   73253.198943     6.505751    2762.949661    -0.081025     0.204849   
std    14900.324964    16.777648   17030.106985     1.000000     0.403654   
min    20629.000000     0.000000       0.010000    -0.335340     0.000000   
25%    70968.000000     1.000000      65.000000    -0.323419     0.000000   
50%    80536.000000     3.000000     159.000000    -0.283405     0.000000   
75%    82532.000000     6.000000     550.000000    -0.136182     0.000000   
max    84305.000000   439.000000  469681.000000    38.046035     1.000000   

       Company Revenue  Automated Job Importer      pgm1jan      pgm1feb  \
count     3.217000e+03             3217.000000  3217.000000  3217.000000   
mean      7.105695e+08                0.310538     0.055953     0.058129   
std       6.888938e+09                0.462786     0.739337     1.070310   
min       0.000000e+00                0.000000     0.000000     0.000000   
25%       2.000000e+05                0.000000     0.000000     0.000000   
50%       2.123100e+07                0.000000     0.000000     0.000000   
75%       9.694000e+07                1.000000     0.000000     0.000000   
max       2.745150e+11                1.000000    25.000000    54.000000   

           pgm1mar  ...      PGMCJul      PGMCAug      PGMCSep      PGMCOct  \
count  3217.000000  ...  3217.000000  3217.000000  3217.000000  3217.000000   
mean      0.041654  ...     0.108486     0.119366     0.136773     0.154181   
std       0.699240  ...     0.311042     0.324269     0.343661     0.361178   
min       0.000000  ...     0.000000     0.000000     0.000000     0.000000   
25%       0.000000  ...     0.000000     0.000000     0.000000     0.000000   
50%       0.000000  ...     0.000000     0.000000     0.000000     0.000000   
75%       0.000000  ...     0.000000     0.000000     0.000000     0.000000   
max      27.000000  ...     1.000000     1.000000     1.000000     1.000000   

           PGMCNov  Product PC.1        ofccp     MP_Items    MP_Orders  \
count  3217.000000   3217.000000  3217.000000  3217.000000  3217.000000   
mean      0.172832      0.236245     0.161641    15.257072     9.506994   
std       0.378161      0.424840     0.368179   132.580983    77.300896   
min       0.000000      0.000000     0.000000     0.000000     0.000000   
25%       0.000000      0.000000     0.000000     0.000000     0.000000   
50%       0.000000      0.000000     0.000000     1.000000     1.000000   
75%       0.000000      0.000000     0.000000     4.000000     4.000000   
max       1.000000      1.000000     1.000000  4904.000000  2948.000000   

           stndmkt  
count  3217.000000  
mean     -0.000938  
std       1.000000  
min      -0.150886  
25%      -0.150886  
50%      -0.138488  
75%      -0.100948  
max      37.119716  

[8 rows x 37 columns]

In [5]:
X = df2.drop(columns = ['ID', 'account type', 'Billing State/Province', 'Last Activity', 'ATS System', 
                        'Product O', 'Product MKT', 'Product PC', 'Product P1', 'Revenue Range', 'Industry', 'ofccp'])
y = df2['Product P1']
y_2 = df2['Product PC']
y_3 = df2['ofccp']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = LogisticRegression()
model.fit(X_train, y_train)
predictions = model.predict(X_test)

score = accuracy_score(y_test, predictions)
print(score)

#  So let's explain what happened. I did some basic dropping of columns that aren't float based to get a basic readout of what a
#  model such as logistic regression can do based on the following columns: "SF contacts, Employees, stand rank, company revenue
#  Automated Job Importer, pgm1jan through pgm1dec, pgm1total, PGMCJan through PGMC Nov (assuming fiscal year stops at Nov.),
#  Product PC, MP_Items, MP_Orders, stndmkt

#  The accuracy score varies from roughly 75 to 85 percent (Self-ran hundreds of times)

probability_predictions = model.predict_proba(X)
print(probability_predictions)

#  If I understand the predict probability method correctly, this is the probability of an entry with an arbitrary P1 value input
#  that our model is then attempting to output, with .5, .5 being the worse: the model doesn't know. However, with a high
#  accuracy score, I assume that model is operating as intended

sliced_probabilities = np.array(probability_predictions[0:, 0:1])
print(sliced_probabilities)

#  Formatting our data for outputting the result to a pandas dataframe

sliced_probabilities.reshape(1,3217)
df3["P1 Probability"] = sliced_probabilities

df3

#Run this cell once for P1 Probabilities

0.8059006211180124
[[0.70618103 0.29381897]
 [0.77597433 0.22402567]
 [0.5        0.5       ]
 ...
 [0.54964138 0.45035862]
 [0.50379954 0.49620046]
 [0.5        0.5       ]]
[[0.70618103]
 [0.77597433]
 [0.5       ]
 ...
 [0.54964138]
 [0.50379954]
 [0.5       ]]


ID    account type  SF contacts Billing State/Province  \
0     55435  RM - Strategic          156                     OH   
1     37015  RM - Strategic           24                     CA   
2     39156     RM - Senior           12                     MA   
3     39395  RM - Strategic           50                     AZ   
4     22406  RM - Strategic           48                     TX   
...     ...             ...          ...                    ...   
3212  80035      SMB - Lead            3                     CA   
3213  80005      SMB - Lead            3                     CA   
3214  79942      SMB - Lead            1                     KS   
3215  80037     RM - Junior            6                     CA   
3216  79967            AE 2            4                     PA   

            Last Activity  Employees   ATS System  stand rank Product O  \
0     2020-12-23 00:00:00     4400.0        iCims    6.786257  Customer   
1     2020-10-29 00:00:00     7094.0      Jobvite    0.017874  Prospect   
2     2020-12-21 00:00:00      467.0        iCims    2.849505  Customer   
3     2020-12-16 00:00:00     3600.0        iCims    1.118288  Customer   
4     2020-12-09 00:00:00    24337.0     Taleo BE    5.714316  Prospect   
...                   ...        ...          ...         ...       ...   
3212  2020-12-18 00:00:00      283.0        iCims   -0.073011      NONE   
3213  2020-10-29 00:00:00       27.0  ZohoRecruit   -0.261462      NONE   
3214  2020-08-19 00:00:00     1250.0      Jobvite   -0.255009      NONE   
3215  2020-12-18 00:00:00      124.0   Greenhouse   -0.300109      NONE   
3216  2020-10-29 00:00:00     2929.0       JazzHR   -0.181511      NONE   

     Product MKT  ... PGMCAug  PGMCSep  PGMCOct PGMCNov  Product PC.1 ofccp  \
0       Customer  ...       0        0        0       0             0     1   
1           NONE  ...       0        0        0       0             0     0   
2       Customer  ...       0        0        0       0             0     1   
3       Customer  ...       0        0        0       0             0     1   
4       Customer  ...       1        1        1       1             1     0   
...          ...  ...     ...      ...      ...     ...           ...   ...   
3212    Prospect  ...       0        0        0       0             1     0   
3213    Prospect  ...       0        0        0       0             0     0   
3214    Prospect  ...       0        0        0       0             1     0   
3215    Prospect  ...       0        0        0       0             0     0   
3216    Prospect  ...       0        0        0       0             0     0   

      MP_Items  MP_Orders    stndmkt  P1 Probability  
0          978        464  12.818822        0.706181  
1          315        288   1.908141        0.775974  
2          524        269   3.660920        0.500000  
3          351        252   1.276217        0.907187  
4          988        432   6.811592        0.957017  
...        ...        ...        ...             ...  
3212         0          0  -0.150886        0.508821  
3213         0          0  -0.150886        0.500832  
3214         0          0  -0.150886        0.549641  
3215         0          0  -0.150886        0.503800  
3216         0          0  -0.150886        0.500000  

[3217 rows x 47 columns]

In [6]:
#  Run this cell once for OFCCP Probabilities

X3_train, X3_test, y3_train, y3_test = train_test_split(X, y_3, test_size=0.2)

model3 = LogisticRegression()
model3.fit(X3_train, y3_train)
predictions_3 = model.predict(X3_test)

score3 = accuracy_score(y3_test, predictions_3)
print(score3)

probability_predictions3 = model3.predict_proba(X)
print(probability_predictions3)

sliced_probabilities3 = np.array(probability_predictions3[0:, 0:1])
print(sliced_probabilities3)

sliced_probabilities3.reshape(1,3217)
df3["OFCCP Probability"] = sliced_probabilities3

df3

0.860248447204969
[[0.5321871  0.4678129 ]
 [0.54553767 0.45446233]
 [0.5        0.5       ]
 ...
 [0.50732209 0.49267791]
 [0.50055863 0.49944137]
 [0.5        0.5       ]]
[[0.5321871 ]
 [0.54553767]
 [0.5       ]
 ...
 [0.50732209]
 [0.50055863]
 [0.5       ]]


ID    account type  SF contacts Billing State/Province  \
0     55435  RM - Strategic          156                     OH   
1     37015  RM - Strategic           24                     CA   
2     39156     RM - Senior           12                     MA   
3     39395  RM - Strategic           50                     AZ   
4     22406  RM - Strategic           48                     TX   
...     ...             ...          ...                    ...   
3212  80035      SMB - Lead            3                     CA   
3213  80005      SMB - Lead            3                     CA   
3214  79942      SMB - Lead            1                     KS   
3215  80037     RM - Junior            6                     CA   
3216  79967            AE 2            4                     PA   

            Last Activity  Employees   ATS System  stand rank Product O  \
0     2020-12-23 00:00:00     4400.0        iCims    6.786257  Customer   
1     2020-10-29 00:00:00     7094.0      Jobvite    0.017874  Prospect   
2     2020-12-21 00:00:00      467.0        iCims    2.849505  Customer   
3     2020-12-16 00:00:00     3600.0        iCims    1.118288  Customer   
4     2020-12-09 00:00:00    24337.0     Taleo BE    5.714316  Prospect   
...                   ...        ...          ...         ...       ...   
3212  2020-12-18 00:00:00      283.0        iCims   -0.073011      NONE   
3213  2020-10-29 00:00:00       27.0  ZohoRecruit   -0.261462      NONE   
3214  2020-08-19 00:00:00     1250.0      Jobvite   -0.255009      NONE   
3215  2020-12-18 00:00:00      124.0   Greenhouse   -0.300109      NONE   
3216  2020-10-29 00:00:00     2929.0       JazzHR   -0.181511      NONE   

     Product MKT  ... PGMCSep  PGMCOct  PGMCNov Product PC.1  ofccp MP_Items  \
0       Customer  ...       0        0        0            0      1      978   
1           NONE  ...       0        0        0            0      0      315   
2       Customer  ...       0        0        0            0      1      524   
3       Customer  ...       0        0        0            0      1      351   
4       Customer  ...       1        1        1            1      0      988   
...          ...  ...     ...      ...      ...          ...    ...      ...   
3212    Prospect  ...       0        0        0            1      0        0   
3213    Prospect  ...       0        0        0            0      0        0   
3214    Prospect  ...       0        0        0            1      0        0   
3215    Prospect  ...       0        0        0            0      0        0   
3216    Prospect  ...       0        0        0            0      0        0   

      MP_Orders    stndmkt  P1 Probability  OFCCP Probability  
0           464  12.818822        0.706181           0.532187  
1           288   1.908141        0.775974           0.545538  
2           269   3.660920        0.500000           0.500000  
3           252   1.276217        0.907187           0.583019  
4           432   6.811592        0.957017           0.612117  
...         ...        ...             ...                ...  
3212          0  -0.150886        0.508821           0.501297  
3213          0  -0.150886        0.500832           0.500122  
3214          0  -0.150886        0.549641           0.507322  
3215          0  -0.150886        0.503800           0.500559  
3216          0  -0.150886        0.500000           0.500000  

[3217 rows x 48 columns]

In [7]:
#  Run this cell once for Product PC Probabilities

X2_train, X2_test, y2_train, y2_test = train_test_split(X, y_2, test_size=0.2)

model2 = DecisionTreeClassifier()
model2.fit(X2_train, y2_train)
predictions_2 = model.predict(X2_test)

score2 = accuracy_score(y2_test, predictions_2)
print(score2)

probability_predictions2 = model2.predict_proba(X)
print(probability_predictions2)

sliced_probabilities2 = np.array(probability_predictions2[0:, 0:1])
print(sliced_probabilities2)

sliced_probabilities2.reshape(1,3217)
df3["PC Probabilities"] = sliced_probabilities2

df3

0.0
[[0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 ...
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


ID    account type  SF contacts Billing State/Province  \
0     55435  RM - Strategic          156                     OH   
1     37015  RM - Strategic           24                     CA   
2     39156     RM - Senior           12                     MA   
3     39395  RM - Strategic           50                     AZ   
4     22406  RM - Strategic           48                     TX   
...     ...             ...          ...                    ...   
3212  80035      SMB - Lead            3                     CA   
3213  80005      SMB - Lead            3                     CA   
3214  79942      SMB - Lead            1                     KS   
3215  80037     RM - Junior            6                     CA   
3216  79967            AE 2            4                     PA   

            Last Activity  Employees   ATS System  stand rank Product O  \
0     2020-12-23 00:00:00     4400.0        iCims    6.786257  Customer   
1     2020-10-29 00:00:00     7094.0      Jobvite    0.017874  Prospect   
2     2020-12-21 00:00:00      467.0        iCims    2.849505  Customer   
3     2020-12-16 00:00:00     3600.0        iCims    1.118288  Customer   
4     2020-12-09 00:00:00    24337.0     Taleo BE    5.714316  Prospect   
...                   ...        ...          ...         ...       ...   
3212  2020-12-18 00:00:00      283.0        iCims   -0.073011      NONE   
3213  2020-10-29 00:00:00       27.0  ZohoRecruit   -0.261462      NONE   
3214  2020-08-19 00:00:00     1250.0      Jobvite   -0.255009      NONE   
3215  2020-12-18 00:00:00      124.0   Greenhouse   -0.300109      NONE   
3216  2020-10-29 00:00:00     2929.0       JazzHR   -0.181511      NONE   

     Product MKT  ... PGMCOct  PGMCNov  Product PC.1 ofccp  MP_Items  \
0       Customer  ...       0        0             0     1       978   
1           NONE  ...       0        0             0     0       315   
2       Customer  ...       0        0             0     1       524   
3       Customer  ...       0        0             0     1       351   
4       Customer  ...       1        1             1     0       988   
...          ...  ...     ...      ...           ...   ...       ...   
3212    Prospect  ...       0        0             1     0         0   
3213    Prospect  ...       0        0             0     0         0   
3214    Prospect  ...       0        0             1     0         0   
3215    Prospect  ...       0        0             0     0         0   
3216    Prospect  ...       0        0             0     0         0   

     MP_Orders    stndmkt  P1 Probability  OFCCP Probability  PC Probabilities  
0          464  12.818822        0.706181           0.532187               0.0  
1          288   1.908141        0.775974           0.545538               0.0  
2          269   3.660920        0.500000           0.500000               0.0  
3          252   1.276217        0.907187           0.583019               0.0  
4          432   6.811592        0.957017           0.612117               1.0  
...        ...        ...             ...                ...               ...  
3212         0  -0.150886        0.508821           0.501297               0.0  
3213         0  -0.150886        0.500832           0.500122               0.0  
3214         0  -0.150886        0.549641           0.507322               0.0  
3215         0  -0.150886        0.503800           0.500559               0.0  
3216         0  -0.150886        0.500000           0.500000               0.0  

[3217 rows x 49 columns]

In [10]:
#Run this to export the dataframe to a new excel file

with pd.ExcelWriter("Company_Data_Set_New.xlsx") as writer:
    df3.to_excel(writer)